# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
  
- script: npm install
  displayName: 'installing dependencies'

- script: npm test
  displayName: 'unit testing'

- script: npm run test:integration
  displayName: 'e2e testing'

- script: npm run build
  displayName: 'bundling richtext.min.js'