# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
  
- script: npm install
  displayName: 'installing dependencies'

#- script: npm run lint
#  displayName: 'Linting'

#- script: npm test
#  displayName: 'Unit Tests'

#- script: npm run test:integration
#  displayName: 'E2E Tests'

- script: npm run build
  displayName: 'Building richtext.min.js'

- task: CopyFiles@2
  inputs:
    SourceFolder: './dist'
    Contents: 'richtext.min.js'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'