# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: npm install
  displayName: 'installing dependencies'

- script: npm lint
  displayName: 'Linting'

- script: npm tests
  displayName: 'Unit Tests'

- script: npm run test:integration
  displayName: 'E2E Tests'

- script: npm run build
  displayName: 'Building richtext.min.js'
